export const women = [
  { name: "Marie Curie", category: "Science", wiki: "https://fr.wikipedia.org/wiki/Marie_Curie" },
  { name: "Rosa Parks", category: "Activism", wiki: "https://fr.wikipedia.org/wiki/Rosa_Parks" },
  { name: "Frida Kahlo", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Frida_Kahlo" },
  { name: "Amelia Earhart", category: "Adventure", wiki: "https://fr.wikipedia.org/wiki/Amelia_Earhart" },
  { name: "Ada Lovelace", category: "Science", wiki: "https://fr.wikipedia.org/wiki/Ada_Lovelace" },
  { name: "Malala Yousafzai", category: "Activism", wiki: "https://fr.wikipedia.org/wiki/Malala_Yousafzai" },
  { name: "Serena Williams", category: "Sports", wiki: "https://fr.wikipedia.org/wiki/Serena_Williams" },
  { name: "Cléopâtre", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/Cl%C3%A9op%C3%A2tre_VII" },
  { name: "Elizabeth II", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/%C3%89lisabeth_II" },
  { name: "Mère Teresa", category: "Activism", wiki: "https://fr.wikipedia.org/wiki/M%C3%A8re_Teresa" },
  { name: "Jane Austen", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Jane_Austen" },
  { name: "Marilyn Monroe", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Marilyn_Monroe" },
  { name: "Florence Nightingale", category: "Science", wiki: "https://fr.wikipedia.org/wiki/Florence_Nightingale" },
  { name: "Jeanne d'Arc", category: "History", wiki: "https://fr.wikipedia.org/wiki/Jeanne_d%27Arc" },
  { name: "Anne Frank", category: "History", wiki: "https://fr.wikipedia.org/wiki/Anne_Frank" },
  { name: "Oprah Winfrey", category: "Media", wiki: "https://fr.wikipedia.org/wiki/Oprah_Winfrey" },
  { name: "Indira Gandhi", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/Indira_Gandhi" },
  { name: "Margaret Thatcher", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/Margaret_Thatcher" },
  { name: "Coco Chanel", category: "Fashion", wiki: "https://fr.wikipedia.org/wiki/Coco_Chanel" },
  { name: "Audrey Hepburn", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Audrey_Hepburn" },
  { name: "Maya Angelou", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Maya_Angelou" },
  { name: "J.K. Rowling", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/J._K._Rowling" },
  { name: "Lady Diana", category: "Activism", wiki: "https://fr.wikipedia.org/wiki/Diana_Spencer" },
  { name: "Michelle Obama", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/Michelle_Obama" },
  { name: "Ruth Bader Ginsburg", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/Ruth_Bader_Ginsburg" },
  { name: "Greta Thunberg", category: "Activism", wiki: "https://fr.wikipedia.org/wiki/Greta_Thunberg" },
  { name: "Beyoncé", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Beyonc%C3%A9" },
  { name: "Madonna", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Madonna" },
  { name: "Grace Hopper", category: "Science", wiki: "https://fr.wikipedia.org/wiki/Grace_Hopper" },
  { name: "Hedy Lamarr", category: "Science", wiki: "https://fr.wikipedia.org/wiki/Hedy_Lamarr" },
  { name: "Katherine Johnson", category: "Science", wiki: "https://fr.wikipedia.org/wiki/Katherine_Johnson" },
  { name: "Rosalind Franklin", category: "Science", wiki: "https://fr.wikipedia.org/wiki/Rosalind_Franklin" },
  { name: "Valentina Terechkova", category: "Science", wiki: "https://fr.wikipedia.org/wiki/Valentina_Terechkova" },
  { name: "Simone de Beauvoir", category: "Philosophy", wiki: "https://fr.wikipedia.org/wiki/Simone_de_Beauvoir" },
  { name: "Virginia Woolf", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Virginia_Woolf" },
  { name: "Emily Dickinson", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Emily_Dickinson" },
  { name: "Aretha Franklin", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Aretha_Franklin" },
  { name: "Whitney Houston", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Whitney_Houston" },
  { name: "Billie Holiday", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Billie_Holiday" },
  { name: "Eleanor Roosevelt", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/Eleanor_Roosevelt" },
  { name: "Angela Merkel", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/Angela_Merkel" },
  { name: "Benazir Bhutto", category: "Politics", wiki: "https://fr.wikipedia.org/wiki/Benazir_Bhutto" },
  { name: "Emmeline Pankhurst", category: "Activism", wiki: "https://fr.wikipedia.org/wiki/Emmeline_Pankhurst" },
  { name: "Sojourner Truth", category: "Activism", wiki: "https://fr.wikipedia.org/wiki/Sojourner_Truth" },
  { name: "Harriet Tubman", category: "Activism", wiki: "https://fr.wikipedia.org/wiki/Harriet_Tubman" },
  { name: "Mary Wollstonecraft", category: "Philosophy", wiki: "https://fr.wikipedia.org/wiki/Mary_Wollstonecraft" },
  { name: "Agatha Christie", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Agatha_Christie" },
  { name: "Toni Morrison", category: "Arts", wiki: "https://fr.wikipedia.org/wiki/Toni_Morrison" },
  { name: "Zaha Hadid", category: "Architecture", wiki: "https://fr.wikipedia.org/wiki/Zaha_Hadid" },
  { name: "Simone Biles", category: "Sports", wiki: "https://fr.wikipedia.org/wiki/Simone_Biles" }
];
